### PR TITLE
Big ID update

### PR DESCRIPTION
**Pull request by matz-e**
Weed out uneeded IDs and update the remaining ele and mu IDs.

Shuffle some code around, simplify the switch logic. I think there were some corner-cases where the fakeable/mvabased ID could have included leptons that did not pass preselection.

I'll test some more and then merge if there are no comments…

### CODE REVIEW

**Comment by zctao** [comment]
I've also tested the updates with my analyzer and everything looks good.

**Comment by matz-e** [comment]
Thanks, @zctao! @muell149, any comments? Since this brings us closer to a sync with Thomas, I'd like to merge it before the master diverges.

IIRC, you switched your code over to using mvabased et al, right? Then this should hopefully work… maybe I'll just clone your repo and see if it compiles…

**Comment by muell149** [comment]
I saw this, I think this is all good, since I don't forsee any  need to re-sync on anything done for moriond, and we'll be one step closer to sync'ing when we have to do it again soon.  OK for me!

**Comment by matz-e** [comment]
Thanks, wanted to make sure you had a look at this. I'm not 100% synced up, but the cuts are all matching our TWiki. Further tweaking will be done in `master`.

**Pull request merged**
